apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
  - ../../base

patches:
  - target:
      kind: ConfigMap
      name: docflow-config
    patch: |-
      - op: replace
        path: /data/CLOUD_PROVIDER
        value: gcp
      - op: replace
        path: /data/ENVIRONMENT
        value: production
  - target:
      kind: StatefulSet
      name: postgres
    patch: |-
      apiVersion: apps/v1
      kind: StatefulSet
      metadata:
        name: postgres
      $patch: delete
  - target:
      kind: Service
      name: postgres
    patch: |-
      apiVersion: v1
      kind: Service
      metadata:
        name: postgres
      $patch: delete
  - target:
      kind: NetworkPolicy
      name: allow-postgres-from-api
    patch: |-
      apiVersion: networking.k8s.io/v1
      kind: NetworkPolicy
      metadata:
        name: allow-postgres-from-api
      $patch: delete

images:
  - name: docflow/api
    newName: us-central1-docker.pkg.dev/PROJECT/docflow/api
    newTag: "2.0.0"
  - name: docflow/web
    newName: us-central1-docker.pkg.dev/PROJECT/docflow/web
    newTag: "2.0.0"
