aws_region           = "us-east-1"
aws_profile          = "terraform-role"
project_name         = "doc-power"
environment          = "production"
cluster_name         = "doc-power-prod-cluster"
vpc_cidr             = "10.0.0.0/16"
public_subnets       = ["10.0.1.0/24", "10.0.2.0/24"]
private_subnets      = ["10.0.10.0/24", "10.0.11.0/24"]
allowed_ips_for_api  = ["0.0.0.0/0"]
node_instance_type   = "t3.medium"
node_desired_size    = 2
node_min_size        = 1
node_max_size        = 3
