apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: docflow-storage
  labels:
    app.kubernetes.io/name: storage
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 50Gi
